# Generated by Django 5.2.3 on 2025-07-04 20:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0004_alter_associadomodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalINSSGuiaDoMes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.CharField(choices=[('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro')], max_length=2)),
                ('status_emissao', models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('pago', 'Pago'), ('atrasada', 'Atrasada')], default='pendente', max_length=12)),
                ('status_acesso', models.CharField(choices=[('validar_codigo_acesso', 'Validar Código Acesso'), ('senha_invalida', 'Senha Inválida'), ('nivel_conta_insuficiente', 'Nível Conta Insuficiente'), ('sem_caepf', 'Sem CAEPF'), ('sem_login', 'Sem Login'), ('ok', 'OK')], default='ok', max_length=40)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('processada', models.BooleanField(default=False)),
                ('rodada', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('associado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_associados.associadomodel')),
                ('em_processamento_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inss guia do mes',
                'verbose_name_plural': 'historical inss guia do mess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='INSSGuiaDoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.CharField(choices=[('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro')], max_length=2)),
                ('status_emissao', models.CharField(choices=[('pendente', 'Pendente'), ('emitido', 'Emitido'), ('pago', 'Pago'), ('atrasada', 'Atrasada')], default='pendente', max_length=12)),
                ('status_acesso', models.CharField(choices=[('validar_codigo_acesso', 'Validar Código Acesso'), ('senha_invalida', 'Senha Inválida'), ('nivel_conta_insuficiente', 'Nível Conta Insuficiente'), ('sem_caepf', 'Sem CAEPF'), ('sem_login', 'Sem Login'), ('ok', 'OK')], default='ok', max_length=40)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processada', models.BooleanField(default=False)),
                ('rodada', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_inss', to='app_associados.associadomodel')),
                ('em_processamento_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_inss_em_processamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ano', '-mes', 'associado'],
                'unique_together': {('associado', 'ano', 'mes', 'rodada')},
            },
        ),
        migrations.CreateModel(
            name='ProcessamentoINSSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.CharField(choices=[('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro')], max_length=2)),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('usuario_processando', 'Usuário Processando'), ('Processada', 'Processada'), ('aguardando_processamento', 'Aguardando Processamento')], default='usuario_processando', max_length=30)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('indice_atual', models.PositiveIntegerField(default=0)),
                ('total_associados', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos_inss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_em'],
                'unique_together': {('ano', 'mes', 'rodada', 'usuario')},
            },
        ),
    ]
