# Generated by Django 5.2.3 on 2025-07-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinssguiadomes',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='historicalinssguiadomes',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='inssguiadomes',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='inssguiadomes',
            name='observacoes',
        ),
    ]
