# Generated by Django 5.2.3 on 2025-06-29 15:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0004_alter_associadomodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True, verbose_name='Ano da Anuidade')),
                ('valor_anuidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Anuidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anuidade',
                'verbose_name_plural': 'Anuidades',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='AnuidadeAssociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('pago', models.BooleanField(default=False, verbose_name='Anuidade Paga')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_associados.associadomodel')),
                ('anuidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuidades_associados', to='app_anuidades.anuidademodel')),
            ],
            options={
                'verbose_name': 'Anuidade do Associado',
                'verbose_name_plural': 'Anuidades dos Associados',
                'ordering': ['associado'],
                'unique_together': {('anuidade', 'associado')},
            },
        ),
        migrations.CreateModel(
            name='DescontoAnuidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('motivo', models.TextField(verbose_name='Motivo do Desconto')),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('anuidade_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='app_anuidades.anuidadeassociado', verbose_name='Anuidade Associado')),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
            ],
            options={
                'verbose_name': 'Desconto na Anuidade',
                'verbose_name_plural': 'Descontos nas Anuidades',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('comprovante_up', models.FileField(blank=True, null=True, upload_to='comprovantes_anuidades/', verbose_name='Comprovante do Pagamento')),
                ('anuidade_associado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_anuidades.anuidadeassociado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
        ),
    ]
