# Generated by Django 5.2.3 on 2025-06-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anuidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descontoanuidade',
            name='motivo',
            field=models.CharField(max_length=1000, verbose_name='Motivo do Desconto'),
        ),
    ]
