# Generated by Django 5.2.3 on 2025-06-27 20:00

import app_uploads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadsDocs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_custom', models.CharField(blank=True, max_length=100, verbose_name='Classificação Livre')),
                ('arquivo', models.FileField(upload_to=app_uploads.models.upload_to_path)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('proprietario_object_id', models.PositiveIntegerField()),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proprietario_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_uploads.tipodocumentoup')),
            ],
            options={
                'verbose_name': 'Documento Enviado',
                'verbose_name_plural': 'Uploads de Documentos',
                'ordering': ['-data_envio'],
            },
        ),
    ]
