# Generated by Django 5.2.3 on 2025-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumentoup',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
