# Generated by Django 5.2.3 on 2025-07-14 22:07

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associacao', '0005_alter_reparticoesmodel_nome_reparticao_and_more'),
        ('app_associados', '0004_alter_associadomodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServicoModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('natureza_servico', models.CharField(choices=[('assessoria', 'Assessoria'), ('consultoria', 'Consultoria'), ('emissao_documento', 'Emissão e Documento')], max_length=100, verbose_name='Natureza do Serviço')),
                ('tipo_servico', models.CharField(choices=[('assessoria_administrativa', 'Assessoria Administrativa (Recursos)'), ('assessoria_processo_paa', 'Assessoria Processo PAA'), ('assessoria_processo_pronaf', 'Assessoria Processo PRONAF'), ('emissao_tie', 'Emissão de TIE'), ('emissao_rgp', 'Emissão de RGP'), ('emissao_licanca_pesca', 'Emissão Licença Pesca'), ('consultoria_geral', 'Consultoria_geral')], max_length=100, verbose_name='Natureza do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_inicio', models.DateTimeField(blank=True, editable=False)),
                ('status_servico', models.CharField(max_length=40, verbose_name='Status do Serviço')),
                ('content', models.TextField(blank=True, null=True)),
                ('ultima_alteracao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('associacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('associado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_associados.associadomodel', verbose_name='Associado')),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reparticao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
            ],
            options={
                'verbose_name': 'historical servico model',
                'verbose_name_plural': 'historical servico models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza_servico', models.CharField(choices=[('assessoria', 'Assessoria'), ('consultoria', 'Consultoria'), ('emissao_documento', 'Emissão e Documento')], max_length=100, verbose_name='Natureza do Serviço')),
                ('tipo_servico', models.CharField(choices=[('assessoria_administrativa', 'Assessoria Administrativa (Recursos)'), ('assessoria_processo_paa', 'Assessoria Processo PAA'), ('assessoria_processo_pronaf', 'Assessoria Processo PRONAF'), ('emissao_tie', 'Emissão de TIE'), ('emissao_rgp', 'Emissão de RGP'), ('emissao_licanca_pesca', 'Emissão Licença Pesca'), ('consultoria_geral', 'Consultoria_geral')], max_length=100, verbose_name='Natureza do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('status_servico', models.CharField(max_length=40, verbose_name='Status do Serviço')),
                ('content', models.TextField(blank=True, null=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('associacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_associacao', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_associados.associadomodel', verbose_name='Associado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_reparticao', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='app_servicos.servicomodel')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaFinanceiraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro')], max_length=10, verbose_name='Forma de Pagamento')),
                ('parcelamento', models.CharField(choices=[('avista', 'Pagamento à Vista'), ('duas_parcelas', 'Duas Parcelas'), ('tres_parcelas', 'Três Parcelas')], max_length=15, verbose_name='Parcelamento')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', editable=False, max_length=10, verbose_name='Status do Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('pago', models.BooleanField(default=False)),
                ('valor_pagamento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Pago')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_servico', to='app_servicos.servicomodel')),
            ],
        ),
    ]
