# Generated by Django 5.2.3 on 2025-07-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0002_alter_historicalservicomodel_tipo_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceiramodel',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
