# Generated by Django 5.2.3 on 2025-07-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0003_alter_entradafinanceiramodel_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoentrada',
            name='comprovante_up',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante do Pagamento'),
        ),
    ]
