# Generated by Django 5.2.3 on 2025-07-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0004_pagamentoentrada_comprovante_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicomodel',
            name='tipo_servico',
            field=models.CharField(choices=[('assessoria_administrativa', 'Assessoria Administrativa (Recursos)'), ('assessoria_processo_paa', 'Assessoria Processo PAA'), ('assessoria_processo_pronaf', 'Assessoria Processo PRONAF'), ('emissao_tie', 'Emissão de TIE'), ('emissao_rgp', 'Emissão de RGP'), ('emissao_licanca_pesca', 'Emissão Licença Pesca'), ('emissao_pop', 'Emissão Carteira POP'), ('consultoria_geral', 'Consultoria Geral')], max_length=100, verbose_name='Tipo Serviço'),
        ),
        migrations.AlterField(
            model_name='servicomodel',
            name='tipo_servico',
            field=models.CharField(choices=[('assessoria_administrativa', 'Assessoria Administrativa (Recursos)'), ('assessoria_processo_paa', 'Assessoria Processo PAA'), ('assessoria_processo_pronaf', 'Assessoria Processo PRONAF'), ('emissao_tie', 'Emissão de TIE'), ('emissao_rgp', 'Emissão de RGP'), ('emissao_licanca_pesca', 'Emissão Licença Pesca'), ('emissao_pop', 'Emissão Carteira POP'), ('consultoria_geral', 'Consultoria Geral')], max_length=100, verbose_name='Tipo Serviço'),
        ),
    ]
