# Generated by Django 5.2.3 on 2025-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0005_alter_historicalservicomodel_tipo_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentoentrada',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
