# Generated by Django 5.2.3 on 2025-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0002_alter_associacaomodel_uf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacaomodel',
            name='diretores',
            field=models.ManyToManyField(blank=True, null=True, related_name='diretores_associacao', to='app_associacao.integrantesmodel', verbose_name='Diretores'),
        ),
    ]
