# Generated by Django 5.2.3 on 2025-06-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0003_alter_associacaomodel_diretores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associacaomodel',
            name='diretores',
            field=models.ManyToManyField(blank=True, related_name='diretores_associacao', to='app_associacao.integrantesmodel', verbose_name='Diretores'),
        ),
    ]
