# Generated by Django 5.2.3 on 2025-06-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associacao', '0004_alter_associacaomodel_diretores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparticoesmodel',
            name='nome_reparticao',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome da Repartição'),
        ),
        migrations.AddConstraint(
            model_name='reparticoesmodel',
            constraint=models.UniqueConstraint(fields=('associacao', 'nome_reparticao'), name='unique_reparticao_por_associacao'),
        ),
    ]
