# Generated by Django 5.2.3 on 2025-06-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superusuário'), ('admin_associacao', 'Administrador Associação'), ('diretor', 'Diretor'), ('presidente', 'Presidente'), ('delagado', 'Delegado'), ('financeiro', 'Financeiro'), ('recursos_humanos', 'Recursos Humanos'), ('auxiliar_associacao', 'Auxilir Associação'), ('auxiliar_reparticao', 'Auxiliar Repartição'), ('auxiliar_extra', 'Auxiliar Extra'), ('cliente_vip', 'Cliente VIP'), ('cliente', 'Cliente'), ('Associado', 'Associado')], default='cliente', max_length=20),
        ),
    ]
