# Generated by Django 5.2.3 on 2025-07-06 15:29

import app_defeso.models
import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0004_alter_associadomodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecretosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número do Decreto (Ex: 8.424/2015)', max_length=50, unique=True)),
                ('ementa', models.TextField(blank=True, help_text='Ementa do Decreto', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de publicação no DOU', null=True)),
                ('link_dou', models.URLField(blank=True, help_text='Link para a publicação no Diário Oficial da União', null=True)),
            ],
            options={
                'verbose_name': 'Decreto Federal',
                'verbose_name_plural': 'Decretos Federais',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=100, unique=True)),
                ('nome_popular', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='InstrucoesNormativasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da Instrução Normativa (Ex: 77/2015)', max_length=50, unique=True)),
                ('orgao_emissor', models.CharField(help_text='Órgão que emitiu a Instrução Normativa (Ex: INSS)', max_length=100)),
                ('ementa', models.TextField(blank=True, help_text='Ementa da Instrução Normativa', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de publicação', null=True)),
                ('link_publicacao', models.URLField(blank=True, help_text='Link para a publicação oficial', null=True)),
            ],
            options={
                'verbose_name': 'Instrução Normativa',
                'verbose_name_plural': 'Instruções Normativas',
            },
        ),
        migrations.CreateModel(
            name='LeiFederalPrevidenciaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da Lei (Ex: 10.779/2003)', max_length=50, unique=True)),
                ('ementa', models.TextField(blank=True, help_text='Ementa da Lei', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de publicação no DOU', null=True)),
                ('link_dou', models.URLField(blank=True, help_text='Link para a publicação no Diário Oficial da União', null=True)),
            ],
            options={
                'verbose_name': 'Lei Federal Previdenciária',
                'verbose_name_plural': 'Leis Federais Previdenciárias',
            },
        ),
        migrations.CreateModel(
            name='PortariasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da Portaria (Ex: 154/2011)', max_length=50)),
                ('ano', models.PositiveIntegerField(help_text='Ano da Portaria')),
                ('orgao_emissor', models.CharField(help_text='Órgão que emitiu a Portaria (Ex: MPA, MMA, INSS, IEF-MG)', max_length=100)),
                ('tipo', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], default='FEDERAL', help_text='Tipo de Portaria (Federal, Estadual, Municipal)', max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('Undefined ', 'Undefined')], help_text='UF, se for uma Portaria Estadual', max_length=20, null=True)),
                ('ementa', models.TextField(blank=True, help_text='Ementa da Portaria', null=True)),
                ('data_publicacao', models.DateField(blank=True, help_text='Data de publicação', null=True)),
                ('link_publicacao', models.URLField(blank=True, help_text='Link para a publicação oficial', null=True)),
            ],
            options={
                'verbose_name': 'Portaria',
                'verbose_name_plural': 'Portarias',
                'unique_together': {('numero', 'ano', 'orgao_emissor', 'tipo', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='SeguroDefesoBeneficioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('Undefined ', 'Undefined')], help_text='Estado onde o associado reside e o defeso se aplica', max_length=20)),
                ('ano_concessao', models.PositiveIntegerField(default=2025, help_text='Ano de concessão do benefício')),
                ('data_inicio', models.DateField(help_text='Data de início do período de defeso para o benefício')),
                ('data_fim', models.DateField(help_text='Data de fim do período de defeso para o benefício')),
                ('decreto_regulamentador', models.ForeignKey(blank=True, help_text='Decreto que regulamenta a lei (Ex: Decreto nº 12.527/2025)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_defeso_decreto', to='app_defeso.decretosmodel')),
                ('especie_alvo', models.ForeignKey(blank=True, help_text='Espécie para a qual o defeso foi concedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_defeso.especie')),
                ('instrucao_normativa', models.ForeignKey(blank=True, help_text='Instrução Normativa aplicável (Ex: IN do INSS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_defeso_in', to='app_defeso.instrucoesnormativasmodel')),
                ('lei_federal', models.ForeignKey(blank=True, help_text='Lei Federal base para o benefício (Ex: Lei nº 10.779/2003)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_defeso_lei', to='app_defeso.leifederalprevidenciaria')),
                ('portaria_especifica', models.ForeignKey(blank=True, help_text='Portaria específica que define o período de defeso ou regras adicionais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_defeso_portaria', to='app_defeso.portariasmodel')),
            ],
            options={
                'verbose_name': 'Benefício Seguro Defeso',
                'verbose_name_plural': 'Benefícios Seguro Defeso',
                'unique_together': {('especie_alvo', 'data_inicio', 'data_fim')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalControleBeneficioModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('status_pedido', models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO_EM_ANALISE', 'Em Análise'), ('CUMPRIDA_EXIGENCIA_EM_ANALISE', 'Em Análise'), ('CONCEDIDO', 'Concedido'), ('NEGADO', 'Negado'), ('RECURSO', 'Recurso'), ('CANCELADO', 'Cancelado')], default='EM_PREPARO', help_text='Status atual do benefício', max_length=40)),
                ('data_solicitacao', models.DateField(default=datetime.date.today, help_text='Data em que o benefício foi solicitado')),
                ('data_concessao', models.DateField(blank=True, help_text='Data em que o benefício foi efetivamente concedido', null=True)),
                ('motivo_exigencia', models.TextField(blank=True, help_text='Qual a Exigência é o que deve ser feito para cumprir', null=True)),
                ('motivo_negativa', models.TextField(blank=True, help_text='Motivo se o benefício foi negado', null=True)),
                ('anotacoes', models.TextField(blank=True, help_text='Anotações adicionais sobre o benefício', null=True)),
                ('resultado_final', models.TextField(blank=True, null=True)),
                ('comprovante_protocolo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comprovante do Protocolo')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('associado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_associados.associadomodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('beneficio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_defeso.segurodefesobeneficiomodel')),
            ],
            options={
                'verbose_name': 'historical Controle de Benefício',
                'verbose_name_plural': 'historical Controle de Benefícios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodoDefesoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_definidor', models.CharField(help_text='Órgão que definiu o defeso (Ex: IBAMA, MPA/MMA)', max_length=100)),
                ('data_inicio_oficial', models.DateField(help_text='Data de início oficial do defeso')),
                ('data_fim_oficial', models.DateField(help_text='Data de fim oficial do defeso')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('Undefined ', 'Undefined')], help_text='UF, se o defeso for regionalizado', max_length=20, null=True)),
                ('municipios_abrangidos', models.TextField(blank=True, help_text='Lista de municípios abrangidos, se aplicável', null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('especie', models.ForeignKey(help_text='Espécie alvo do defeso', on_delete=django.db.models.deletion.CASCADE, to='app_defeso.especie')),
                ('ato_normativo_oficial', models.ForeignKey(blank=True, help_text='Portaria ou Decreto que estabeleceu este período de defeso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_defeso', to='app_defeso.portariasmodel')),
            ],
            options={
                'verbose_name': 'Período de Defeso Oficial',
                'verbose_name_plural': 'Períodos de Defeso Oficiais',
                'unique_together': {('especie', 'data_inicio_oficial', 'data_fim_oficial', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='ControleBeneficioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('numero_protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('status_pedido', models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO_EM_ANALISE', 'Em Análise'), ('CUMPRIDA_EXIGENCIA_EM_ANALISE', 'Em Análise'), ('CONCEDIDO', 'Concedido'), ('NEGADO', 'Negado'), ('RECURSO', 'Recurso'), ('CANCELADO', 'Cancelado')], default='EM_PREPARO', help_text='Status atual do benefício', max_length=40)),
                ('data_solicitacao', models.DateField(default=datetime.date.today, help_text='Data em que o benefício foi solicitado')),
                ('data_concessao', models.DateField(blank=True, help_text='Data em que o benefício foi efetivamente concedido', null=True)),
                ('motivo_exigencia', models.TextField(blank=True, help_text='Qual a Exigência é o que deve ser feito para cumprir', null=True)),
                ('motivo_negativa', models.TextField(blank=True, help_text='Motivo se o benefício foi negado', null=True)),
                ('anotacoes', models.TextField(blank=True, help_text='Anotações adicionais sobre o benefício', null=True)),
                ('resultado_final', models.TextField(blank=True, null=True)),
                ('comprovante_protocolo', models.FileField(blank=True, null=True, upload_to=app_defeso.models.protocolo_upload_path, verbose_name='Comprovante do Protocolo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='app_associados.associadomodel')),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='app_defeso.segurodefesobeneficiomodel')),
            ],
            options={
                'verbose_name': 'Controle de Benefício',
                'verbose_name_plural': 'Controle de Benefícios',
                'ordering': ['-data_entrada'],
                'unique_together': {('associado', 'beneficio')},
            },
        ),
    ]
