# Generated by Django 5.2.3 on 2025-07-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlebeneficiomodel',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Controle de Benefício', 'verbose_name_plural': 'Controle de Benefícios'},
        ),
        migrations.RemoveField(
            model_name='controlebeneficiomodel',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='historicalcontrolebeneficiomodel',
            name='data_entrada',
        ),
    ]
