# Generated by Django 5.2.3 on 2025-07-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0003_alter_controlebeneficiomodel_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='data_solicitacao',
            field=models.DateField(blank=True, help_text='Data em que o benefício foi solicitado', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontrolebeneficiomodel',
            name='data_solicitacao',
            field=models.DateField(blank=True, help_text='Data em que o benefício foi solicitado', null=True),
        ),
    ]
