# Generated by Django 5.2.3 on 2025-07-07 19:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0004_alter_controlebeneficiomodel_data_solicitacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProcessamentoSeguroDefesoModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('usuario_processando', 'Usuário Processando'), ('Processada', 'Processada'), ('aguardando_processamento', 'Aguardando Processamento')], default='usuario_processando', max_length=30)),
                ('iniciado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('indice_atual', models.PositiveIntegerField(default=0)),
                ('total_associados', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beneficio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app_defeso.segurodefesobeneficiomodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical processamento seguro defeso model',
                'verbose_name_plural': 'historical processamento seguro defeso models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessamentoSeguroDefesoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('usuario_processando', 'Usuário Processando'), ('Processada', 'Processada'), ('aguardando_processamento', 'Aguardando Processamento')], default='usuario_processando', max_length=30)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('indice_atual', models.PositiveIntegerField(default=0)),
                ('total_associados', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos', to='app_defeso.segurodefesobeneficiomodel')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processamentos_seguro_defeso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_em'],
                'unique_together': {('beneficio', 'rodada', 'usuario')},
            },
        ),
    ]
