# Generated by Django 5.2.3 on 2025-07-07 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0005_historicalprocessamentosegurodefesomodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocessamentosegurodefesomodel',
            name='em_processamento_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocessamentosegurodefesomodel',
            name='processada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processamentosegurodefesomodel',
            name='em_processamento_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_defeso_em_processamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processamentosegurodefesomodel',
            name='processada',
            field=models.BooleanField(default=False),
        ),
    ]
