# Generated by Django 5.2.3 on 2025-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0007_controlebeneficiomodel_em_processamento_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebeneficiomodel',
            name='rodada',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalcontrolebeneficiomodel',
            name='rodada',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
