# Generated by Django 5.2.3 on 2025-07-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0008_controlebeneficiomodel_rodada_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segurodefesobeneficiomodel',
            unique_together={('especie_alvo', 'data_inicio', 'data_fim', 'estado')},
        ),
    ]
