# Generated by Django 5.2.3 on 2025-07-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0009_alter_segurodefesobeneficiomodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periododefesooficial',
            name='municipios_abrangidos',
        ),
    ]
