# Generated by Django 5.2.3 on 2025-07-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0010_remove_periododefesooficial_municipios_abrangidos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processamentosegurodefesomodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='processamentosegurodefesomodel',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='processamentosegurodefesomodel',
            name='em_processamento_por',
        ),
        migrations.RemoveField(
            model_name='processamentosegurodefesomodel',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='HistoricalProcessamentoSeguroDefesoModel',
        ),
        migrations.DeleteModel(
            name='ProcessamentoSeguroDefesoModel',
        ),
    ]
