# Generated by Django 5.2.3 on 2025-06-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='bolsa_familia',
            field=models.CharField(blank=True, choices=[('Já recebeu', 'Já recebeu'), ('Nunca recebeu', 'Nunca recebeu'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=50, null=True, verbose_name='Já recebeu Bolsa Família?'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='casa_onde_mora',
            field=models.CharField(blank=True, choices=[('Mora em casa prórpia', 'Mora em pasa prórpia'), ('Mora em casa augada', 'Mora em casa augada'), ('Mora em casa cedida', 'Mora em casa cedida'), ('Mora em casa de terceiros', 'Mora em casa de terceiros'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=50, null=True, verbose_name='Mora em:'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='outra_fonte_renda',
            field=models.CharField(blank=True, choices=[('Não Possui', 'Não Possui'), ('Aposentadoria (INSS)', 'Aposentadoria (INSS)'), ('MEI', 'MEI'), ('Sócio de Empresa', 'Sócio de Empresa'), ('CLT', 'CLT'), ('Servidor Público', 'Servidor Público'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=250, null=True, verbose_name='Possui outra Fonte de Renda?'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='recolhe_inss',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=50, null=True, verbose_name='Recolhe INSS atualmente?'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('associado_lista_ativo', 'Associado Lista Ativos(a)'), ('associado_lista_aposentado', 'Associado Lista Aposentados(a)'), ('candidato', 'Candidato(a)'), ('cliente_especials', 'Cliente Especial'), ('desassociado', 'Desassociado(a)')], default='Candidato(a)', max_length=40, null=True, verbose_name='Status de atividade'),
        ),
    ]
