# Generated by Django 5.2.3 on 2025-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0003_historicalassociadomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('associado_lista_ativo', 'Associado Lista Ativos(a)'), ('associado_lista_aposentado', 'Associado Lista Aposentados(a)'), ('candidato', 'Candidato(a)'), ('cliente_especial', 'Cliente Especial'), ('extra_associado', 'Extra Associado(a)'), ('desassociado', 'Desassociado(a)')], default='Candidato(a)', max_length=40, null=True, verbose_name='Status de atividade'),
        ),
        migrations.AlterField(
            model_name='historicalassociadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('associado_lista_ativo', 'Associado Lista Ativos(a)'), ('associado_lista_aposentado', 'Associado Lista Aposentados(a)'), ('candidato', 'Candidato(a)'), ('cliente_especial', 'Cliente Especial'), ('extra_associado', 'Extra Associado(a)'), ('desassociado', 'Desassociado(a)')], default='Candidato(a)', max_length=40, null=True, verbose_name='Status de atividade'),
        ),
    ]
