# Generated by Django 5.2.3 on 2025-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreapdoano',
            name='status_resposta',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('respondido', 'Respondido')], default='pendente', max_length=12),
        ),
        migrations.AlterField(
            model_name='reapdoano',
            name='status_resposta',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('respondido', 'Respondido')], default='pendente', max_length=12),
        ),
    ]
